name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Build Number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - name: Set Build Number
      run: |
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion Build ${BUILD_NUMBER}" "connection-census/Info.plist"
        
    - name: Test
      run: |
        xcodebuild test -project swifttest.xcodeproj -scheme connection-census -destination 'platform=OS X,arch=x86_64'
        
    - name: Build
      run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          mkdir $PWD/build
          xcodebuild clean archive -archivePath $PWD/build/Build.xcarchive -scheme connection-census -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
    - name: Export Executable
      run: |
        mkdir $PWD/application
        xcodebuild -exportArchive -archivePath $PWD/build/Build.xcarchive -exportOptionsPlist $PWD/ExportOptions.plist -exportPath $PWD/application/
    - name: Package Executable
      run: |
        mkdir $PWD/package
        pkgbuild --install-location /Applications --component $PWD/application/connection-census.app $PWD/package/connection-census.pkg
    - name: Upload Package
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: connection-census-${{ env.BUILD_NUMBER }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ./package/
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
